# Configuração do Sistema de Trading v5.3 - Com Proteções Aprimoradas
# Modo debug (parâmetros mais agressivos)
debug_mode: true

trading:
  symbol: "BTCUSDT"
  min_confidence: 0.40       # Reduzido para permitir mais operações
  max_position_pct: 0.05     # Até 5% do saldo por trade
  
  # NOVAS CONFIGURAÇÕES DE PROTEÇÃO
  allow_reversal_trades: true    # Permite fechar e abrir posição contrária
  close_on_shutdown: false       # Não fecha posições ao desligar
  signal_cooldown: 60           # 60 segundos entre trades

risk:
  max_volatility: 0.50       # Tolerância maior à volatilidade
  max_spread_bps: 50         # Aceita spreads maiores
  max_daily_loss: 0.05       # Permite perder até 5% no dia
  atr_period: 14
  tp_multiplier: 1.5
  sl_multiplier: 1.0
  
  # NOVAS CONFIGURAÇÕES DE RISCO
  max_positions: 1           # Máximo de posições simultâneas
  stop_loss_pct: 2.0         # Stop loss de 2%
  take_profit_pct: 3.0       # Take profit de 3%
  
  # PROTEÇÕES ADICIONAIS (opcional)
  min_risk_reward: 1.5       # Relação risco/recompensa mínima
  max_drawdown: 0.10         # Drawdown máximo de 10%
  
ta:
  # RSI
  rsi_period: 14
  rsi_buy_threshold: 45       # Mais fácil de comprar
  rsi_sell_threshold: 55      # Mais fácil de vender
  rsi_confidence: 0.50
  
  # Médias móveis
  sma_short_period: 9
  sma_long_period: 20
  ema_short_period: 9
  ema_long_period: 20
  sma_cross_confidence: 0.50
  
  # Bollinger Bands
  bb_period: 20
  bb_std_dev: 2.0
  bb_confidence: 0.50
  
  # Pattern Detection
  pattern_confidence: 0.50
  
  # Thresholds para decisão final
  buy_threshold: 0.05
  sell_threshold: 0.05

filters:
  min_volume_multiplier: 0.1     # Permite operar com volume reduzido
  max_recent_volatility: 0.50
  
  # NOVOS FILTROS DE SINAIS
  min_imbalance: 0.75           # Imbalance mínimo de 75% para considerar
  min_volume_usd: 50000         # Volume mínimo de $50k
  whale_trade_threshold: 100000  # Trade > $100k é whale

performance:
  ta_interval_ms: 5000
  main_loop_interval_ms: 1000
  
  # NOVO - Intervalos de verificação
  check_positions_interval: 2000  # Verifica posições a cada 2 segundos
  checkpoint_interval: 300        # Salva checkpoint a cada 5 minutos

# NOVA SEÇÃO - Sistema
system:
  loop_interval: 1              # Intervalo do loop principal em segundos
  enable_alerts: true           # Habilita sistema de alertas
  save_trade_history: true      # Salva histórico de trades
  
# NOVA SEÇÃO - Estatísticas
statistics:
  track_performance: true       # Rastreia performance detalhada
  log_interval: 60             # Loga estatísticas a cada 60 segundos
  save_metrics: true           # Salva métricas em arquivo

# CONFIGURAÇÕES PARA MODO DEBUG
# Estas configurações são mais agressivas para testes
debug_overrides:
  stop_loss_pct: 1.0          # Stop loss menor para debug (1%)
  take_profit_pct: 1.5        # Take profit menor para debug (1.5%)
  signal_cooldown: 30         # Apenas 30s entre trades em debug
  min_confidence: 0.30        # Confiança ainda menor em debug
