# Configuração do Ultra Trading System

# API Configuration
api_key: ""  # Definir via BINANCE_API_KEY env var
api_secret: ""  # Definir via BINANCE_API_SECRET env var
testnet: false

# Trading Configuration
symbol: "BTCUSDT"
base_balance: 10000.0
min_confidence: 0.75
max_position_pct: 0.02
min_order_size: 10.0

# Risk Management
risk:
  max_volatility: 0.05
  max_spread_bps: 20
  max_daily_loss: 0.02
  stop_loss_pct: 0.015
  take_profit_pct: 0.03
  trailing_stop_pct: 0.01
  max_positions: 1
  position_timeout_hours: 24

# Technical Analysis
ta:
  rsi_period: 14
  rsi_buy_threshold: 30
  rsi_sell_threshold: 70
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  bb_period: 20
  bb_std: 2.0
  ema_short: 9
  ema_long: 21
  atr_period: 14
  momentum_period: 10

# Machine Learning
ml:
  features:
    - rsi
    - macd
    - macd_signal
    - bb_upper
    - bb_lower
    - bb_middle
    - volume_ratio
    - price_change
    - volatility
    - momentum
    - support
    - resistance
    - trend_strength
    - volume_profile
    - ema_diff
    - atr
  lookback: 100
  retrain_interval: 1000
  model_type: gradient_boosting
  test_size: 0.2
  n_estimators: 100

# WebSocket Configuration
websocket:
  buffer_size: 1000
  reconnect_delay: 5
  ping_interval: 30
  streams:
    - trade
    - depth20@100ms
    - kline_1m

# System Configuration
system:
  log_level: INFO
  checkpoint_interval: 300
  health_check_interval: 60
  cache_ttl: 60
  rate_limit_per_minute: 1200

# Alerts Configuration
alerts:
  telegram_enabled: true
  telegram_token: ""  # Definir via TELEGRAM_BOT_TOKEN env var
  telegram_chat_id: ""  # Definir via TELEGRAM_CHAT_ID env var
  email_enabled: false
  email_smtp: ""
  email_from: ""
  email_to: ""
