# Configuracao Base
api:
  exchange: "binance"
  testnet: false
  
logging:
  level: "INFO"
  file: "logs/trading.log"

cache:
  backend: "redis"
  ttl: 300

alerts:
  enabled: true
  channels:
    - telegram
