# Configuracao HFT
trading:
  mode: "hft"
  symbol: "BTCBRL"
  interval_seconds: 5
  max_position_btc: 0.00003
  max_position_brl: 20.0
  fee_pct: 0.0001
  dry_run: true

risk:
  take_profit_pct: 0.003
  stop_loss_pct: 0.002
  max_daily_drawdown: 0.02

features:
  lookback_seconds: 60
  momentum_lags: [5, 10, 30]
